ClothesShop/Controllers/CartItemController.cs
using ClothesShop.Migrations;
using ClothesShop.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Internal;
using System.Collections.Generic;
using System.Linq;

namespace ClothesShop.Controllers
{
    public class CartItemController : Controller
    {
        public readonly ShopContext _shopContext;
        public readonly UserManager<AppUser> _userManager;
        public readonly SignInManager<AppUser> _signInManager;
        public List<Category> Category { get; set; }
        public List<CartModel> cartModels { set; get; }
        public CartItemController(ShopContext shopContext, UserManager<AppUser> userManager, SignInManager<AppUser> signInManager)
        {
            _shopContext = shopContext;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public IActionResult Index()
        {
            //lấy loại sản phẩm
            Category = (from a in _shopContext.Categories
                        where a.CateId < 3
                        select a).ToList();
            ViewData["category"] = Category;
            //lấy người dùng hiện tại đang hoạt động
            var userid = _userManager.GetUserId(User);

            //lấy danh sách sản phẩm 
            var z = _shopContext.Products.Select(p => p).ToList();
            ViewData["product"] = z;

            //lấy giỏ hảng theo người dùng đăng nhập
            cartModels = _shopContext.Carts.Where(p => p.UserId == userid).ToList();

            //tính tổng tiền trong giỏ hàng 
            var sum = _shopContext.Carts.Where(s => s.UserId == userid).Sum(x => x.ThanhTien);
            ViewBag.Sum = sum;
            return View(cartModels);
        }

        public IActionResult AddToCart(int id , int SoLuong)
        {
            
            var item = _shopContext.Carts.SingleOrDefault(p => p.Id == id);
            if(item == null)
            {
                if(SoLuong < 1)
                {
                    SoLuong = 1;
                    var product = _shopContext.Products.SingleOrDefault(p => p.Id == id);
                    var total = product.Price.Value - (product.Price.Value * product.Discount.Value);
                    item = new CartModel()
                    {
                        Price = total,
                        Quanlity = SoLuong,
                        ThanhTien = SoLuong * total,
                        Id = id,
                        UserId = _userManager.GetUserId(User),
                    };
                    _shopContext.Carts.Add(item);
                    _shopContext.SaveChanges();
                }
            }
            else
            {
                item.Quanlity++;
                _shopContext.SaveChanges();

            }
            
            return RedirectToAction("Index");
        }
        public IActionResult RemoveItem(int id) 
        {
            var item = _shopContext.Carts.SingleOrDefault(x => x.Id == id);
            if (item != null)
            {
                _shopContext.Carts.Remove(item);
            }
            _shopContext.SaveChanges();
            return RedirectToAction("Index");

        }
        public ActionResult UpdateItem(int id, int SoLuong)
        {
            var item = _shopContext.Carts.SingleOrDefault(x => x.Id == id);
            var product = _shopContext.Products.SingleOrDefault(p => p.Id == id);
            var total = product.Price.Value - (product.Price.Value * product.Discount.Value);
            if (item != null)
            {
                item.Quanlity = SoLuong;
                item.ThanhTien = SoLuong * total;
                _shopContext.SaveChanges();
            }
            
            return RedirectToAction("Index");
        }
    }
}

ClothesShop/Controllers/PayMentController.cs
using ClothesShop.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace ClothesShop.Controllers
{
    public class PayMentController : Controller
    {
        public readonly ShopContext _shopContext;
        public readonly UserManager<AppUser> _userManager;
        public readonly SignInManager<AppUser> _signInManager;

        public PayMentController(ShopContext shopContext, UserManager<AppUser> userManager, SignInManager<AppUser> signInManager)
        {
            _shopContext = shopContext;
            _userManager = userManager;
            _signInManager = signInManager;
        }
        [BindProperty]
        public InputModel Input { get; set; }
        
        public class InputModel
        {
            [Required(ErrorMessage = "Vui lòng nhập tên của bạn")]
            [DisplayName("Họ và Tên")]
            public string FullName { get; set; }

            [Required(ErrorMessage = "Vui lòng nhập email")]
            [EmailAddress]
            public string Email { get; set; }

            [Required(ErrorMessage ="Vui lòng nhập địa chỉ nhà của bạn")]
            [DisplayName("Địa chỉ")]
            public string Address { get; set; }

            [Required(ErrorMessage = "Vui lòng nhập số điện thoại của bạn")]
            [DisplayName("Số điện thoại")]
            public string PhoneNumber { get; set; }
        }
        public List<Category> Category { get; set; }
        public IActionResult Index()
        {
            //lấy loại sản phẩm
            Category = _shopContext.Categories.Where(p => p.CateId <3).ToList();
            ViewData["category"] = Category;
            //lấy người dùng hiện tại đang hoạt động
            var userid = _userManager.GetUserId(User);

            //lấy danh sách sản phẩm
            var product = _shopContext.Products.Select(p => p).ToList();
            ViewData["product"] = product;

            //lấy giỏ hảng theo người dùng đăng nhập
            var cart = _shopContext.Carts.Where(p => p.UserId == userid).ToList();
            ViewData["cart"] = cart;

            //tính tổng tiền trong giỏ hàng 
            var sum = _shopContext.Carts.Where(s => s.UserId == userid).Sum(x => x.ThanhTien);
            ViewBag.Sum = sum;
            return View();
        }
    }
}

ClothesShop/Views/CartItem/Index.cshtml
@model List<ClothesShop.Models.CartModel>
@{
    ViewData["Title"] = "Giỏ Hàng";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var c = ViewData["product"] as List<Product>;
}
<div class="container-fluid pt-5">
    <div class="row px-xl-5">
        <div class="col-lg-8 table-responsive mb-5">
            <table class="table table-bordered text-center mb-0">
                <thead class="bg-secondary text-dark">
                    <tr>
                        <th>Sản Phẩm</th>
                        <th>Giá</th>
                        <th>Số Lượng</th>
                        <th>Thành Tiền</th>
                        <th>Xóa</th>
                    </tr>
                </thead>

                <tbody class="align-middle">
                    @if (Model != null && Model.Any())
                    {
                        @foreach (var p in Model)
                        {

                            <tr>
                                @{
                                    var a = c.FirstOrDefault(product => product.Id == p.Id);
                                }
                                <td class="align-middle" style="text-align:justify"><img src="img/@a.Image" alt="" style="width: 50px;">@a.Name</td>
                                <td class="align-middle">@String.Format("{0:#,###,###}",(Convert.ToDouble((@p.Price))))VNĐ</td>
                                <form asp-action="UpdateItem" asp-controller="CartItem" asp-route-id="@p.Id">
                                <td class="align-middle">
                                    <div class="input-group quantity mx-auto" style="width: 100px;">
                                        <div class="input-group-btn">
                                            <button class="btn btn-sm btn-primary btn-minus">
                                                <i class="fa fa-minus"></i>
                                            </button>
                                        </div>
                                        <input type="text" class="form-control form-control-sm bg-secondary text-center" name="SoLuong" value="@p.Quanlity">

                                        <div class="input-group-btn">
                                            <button class="btn btn-sm btn-primary btn-plus">
                                                <i class="fa fa-plus"></i>
                                            </button>
                                        </div>
                                    </div>
                                </td>
                                </form>
                                <td class="align-middle">@String.Format("{0:#,###,###}",(Convert.ToDouble((p.ThanhTien))))VNĐ</td>
                                <td class="align-middle">
                                    <a asp-controller="CartItem" asp-action="RemoveItem" asp-route-id="@p.Id" class="btn btn-sm btn-primary"><i class="fa fa-times"></i></a>
                                </td>
                            </tr>

                        }
                    }
                    else
                    {
                        <tr>
                            <th class="align-middle">
                                <p class="text-info text-center">Giỏ Hàng Của Bạn Trống!</p>
                            </th>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="col-lg-4">

            <div class="card border-secondary mb-5">
                <div class="card-header bg-secondary border-0">
                    <h4 class="font-weight-semi-bold m-0">Thành Tiền</h4>
                </div>

                <div class="card-footer border-secondary bg-transparent">
                    <div class="d-flex justify-content-between mt-2">
                        <h5 class="font-weight-bold">Tổng Tiền</h5>
                        <h5 class="font-weight-bold">@String.Format("{0:#,###,###}",(Convert.ToDouble(ViewBag.Sum))) VNĐ</h5>
                    </div>
                    <a asp-controller="PayMent" asp-action="Index" class="btn btn-block btn-primary my-3 py-3">Thanh Toán</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Cart End -->