ClothesShop/Controllers/CartItemController.cs
using ClothesShop.Migrations;
using ClothesShop.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Internal;
using System.Collections.Generic;
using System.Linq;

namespace ClothesShop.Controllers
{
    public class CartItemController : Controller
    {
        public readonly ShopContext _shopContext;
        public readonly UserManager<AppUser> _userManager;
        public readonly SignInManager<AppUser> _signInManager;
        public List<Category> Category { get; set; }
        public List<CartModel> cartModels { set; get; }
        public CartItemController(ShopContext shopContext, UserManager<AppUser> userManager, SignInManager<AppUser> signInManager)
        {
            _shopContext = shopContext;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public IActionResult Index()
        {
            //lấy loại sản phẩm
            Category = (from a in _shopContext.Categories
                        where a.CateId < 3
                        select a).ToList();
            ViewData["category"] = Category;
            //lấy người dùng hiện tại đang hoạt động
            var userid = _userManager.GetUserId(User);

            //lấy danh sách sản phẩm 
            var z = _shopContext.Products.Select(p => p).ToList();
            ViewData["product"] = z;

            //lấy giỏ hảng theo người dùng đăng nhập
            cartModels = _shopContext.Carts.Where(p => p.UserId == userid).ToList();

            //tính tổng tiền trong giỏ hàng 
            var sum = _shopContext.Carts.Where(s => s.UserId == userid).Sum(x => x.ThanhTien);
            ViewBag.Sum = sum;
            return View(cartModels);
        }

        public IActionResult AddToCart(int id , int SoLuong)
        {
            
            var item = _shopContext.Carts.SingleOrDefault(p => p.Id == id);
            if(item == null)
            {
                if(SoLuong < 1)
                {
                    SoLuong = 1;
                    var product = _shopContext.Products.SingleOrDefault(p => p.Id == id);
                    var total = product.Price.Value - (product.Price.Value * product.Discount.Value);
                    item = new CartModel()
                    {
                        Price = total,
                        Quanlity = SoLuong,
                        ThanhTien = SoLuong * total,
                        Id = id,
                        UserId = _userManager.GetUserId(User),
                    };
                    _shopContext.Carts.Add(item);
                    _shopContext.SaveChanges();
                }
            }
            else
            {
                item.Quanlity++;
                _shopContext.SaveChanges();

            }
            
            return RedirectToAction("Index");
        }
        public IActionResult RemoveItem(int id) 
        {
            var item = _shopContext.Carts.SingleOrDefault(x => x.Id == id);
            if (item != null)
            {
                _shopContext.Carts.Remove(item);
            }
            _shopContext.SaveChanges();
            return RedirectToAction("Index");

        }
        public ActionResult UpdateItem(int id, int SoLuong)
        {
            var item = _shopContext.Carts.SingleOrDefault(x => x.Id == id);
            var product = _shopContext.Products.SingleOrDefault(p => p.Id == id);
            var total = product.Price.Value - (product.Price.Value * product.Discount.Value);
            if (item != null)
            {
                item.Quanlity = SoLuong;
                item.ThanhTien = SoLuong * total;
                _shopContext.SaveChanges();
            }
            
            return RedirectToAction("Index");
        }
    }
}

ClothesShop/Controllers/ClothesDetailsController.cs
using ClothesShop.Migrations;
using ClothesShop.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
namespace ClothesShop.Controllers
{
    public class ClothesDetailsController : Controller
    {
        private readonly ILogger<ClothesDetailsController> _logger;
        public readonly ShopContext _shopContext;
        public  UserManager<AppUser> _userManager;
        public  SignInManager<AppUser> _signInManager;
        public ClothesDetailsController(ILogger<ClothesDetailsController> logger, ShopContext shopContext , SignInManager<AppUser> signInManager , UserManager<AppUser> userManager)
        {
            _logger = logger;
            _shopContext = shopContext;
            _userManager = userManager;
            _signInManager = signInManager;
        }
        public class Input{
            public string Description { get; set; }
        }
        public List<Category> Category { get; set; }
        public List<AppUser> AppUser { get; set; }
        public Rating Rating { get; set; }
        public Product Products { get; set; }
        public IActionResult Index(int? id, int? totalStars)
        {
            //Load danh muc san pham
            Category = (from a in _shopContext.Categories
                        select a).ToList();
            ViewData["category"] = Category;

            //lấy sản phẩm theo người dùng link vào 
            Products = _shopContext.Products.Where(p => p.Id == id).FirstOrDefault();

            //Lấy sản phẩm cùng loại và bỏ đi sản phẩm có id người dùng xem chi tiết
            var products = (from p in _shopContext.Products
                            where p.CateId == Products.CateId && p.Id != Products.Id
                            select p).ToList();
            ViewData["products"] = products;

            var item = Rating;
            if (totalStars != null)
            {
                item = new Rating
                {
                    Star = (int)totalStars,
                    Name = _userManager.GetUserName(User),
                    Datetime = DateTime.Now.ToString(),
                    Id = (int)id,
                    UserId = _userManager.GetUserId(User)
                };
                _shopContext.Add(item);
                _shopContext.SaveChanges();
                var product = _shopContext.Products.Find(id);
                product.Evaluate = (int?)_shopContext.Rating.Where(r => r.Id == id).Average(s => s.Star);
                _shopContext.SaveChanges();
            }
            var ratings = (from r in _shopContext.Rating
                          where r.Id == id
                          select r).ToList();
            ViewData["ratings"] = ratings;
            var count = _shopContext.Rating.Where(r => r.Id == id).Count();
            ViewBag.Count = count;
            return View(Products);
        }
        

    }
}

ClothesShop/Controllers/HomeController.cs
using ClothesShop.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ClothesShop.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        public readonly ShopContext _shopContext;

        public HomeController(ILogger<HomeController> logger,ShopContext shopContext)
        {
            _logger = logger;
            _shopContext = shopContext;
        }
        public List<Category> Category { get; set; }
        public List<Slide> Slides { get; set; }
        public IActionResult Index(string? searchString)
        {
            var query = (from p in _shopContext.Products
                         where p.Evaluate == 5
                        select p).Take(8).ToList();
            ViewData["query"] = query;
            if (!string.IsNullOrEmpty(searchString))
            {
                return LocalRedirect(Url.Action("Index","Shop"));
                
            }
            Slides = (from a in _shopContext.Slides
                     select a).ToList();
            ViewData["Slide"] = Slides;
            Category = (from a in _shopContext.Categories
                        where a.CateId < 3
                       select a).ToList();
            ViewData["category"] = Category;
            return View();
            
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ClothesShop/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Identity;
@model ClothesShop.Models.Product
@inject UserManager<AppUser> UserManager
@inject SignInManager<AppUser> SignInManager
@{
    ViewData["Title"] = "Trang Chủ";
    var product = ViewData["query"] as List<Product>;
    var slides = ViewData["Slide"] as List<Slide>;
}

<!-- Slide Start -->
<div class="container pt-2 px-0 ">
    <div id="header-carousel" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            
            @foreach(var a in slides)
            {
                @if(a.Id == 1)
                {
                    <div class="carousel-item active" style="height: 410px;">
                        <img class="img-fluid" src="~/img/@a.Img" alt="Image">
                    </div>
                }
                else
                {
                    <div class="carousel-item" style="height: 410px;">
                        <img class="img-fluid" src="~/img/@a.Img" alt="Image">
                    </div>
                }
                

            }
        <a class="carousel-control-prev" href="#header-carousel" data-slide="prev">
            <div class="btn btn-dark" style="width: 45px; height: 45px;">
                <span class="carousel-control-prev-icon mb-n2"></span>
            </div>
        </a>
        <a class="carousel-control-next" href="#header-carousel" data-slide="next">
            <div class="btn btn-dark" style="width: 45px; height: 45px;">
                <span class="carousel-control-next-icon mb-n2"></span>
            </div>
        </a>
    </div>
</div>
</div>
<!-- Featured Start -->
<div class="container-fluid pt-5">
    <div class="row px-xl-5 pb-3">
        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="d-flex align-items-center border mb-4" style="padding: 30px;">
                <h1 class="fa fa-check text-primary m-0 mr-3"></h1>
                <h5 class="font-weight-semi-bold m-0">Quality Product</h5>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="d-flex align-items-center border mb-4" style="padding: 30px;">
                <h1 class="fa fa-shipping-fast text-primary m-0 mr-2"></h1>
                <h5 class="font-weight-semi-bold m-0">Free Shipping</h5>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="d-flex align-items-center border mb-4" style="padding: 30px;">
                <h1 class="fas fa-exchange-alt text-primary m-0 mr-3"></h1>
                <h5 class="font-weight-semi-bold m-0">14-Day Return</h5>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="d-flex align-items-center border mb-4" style="padding: 30px;">
                <h1 class="fa fa-phone-volume text-primary m-0 mr-3"></h1>
                <h5 class="font-weight-semi-bold m-0">24/7 Support</h5>
            </div>
        </div>
    </div>
</div>
<!-- Featured End -->
<!-- Products Start -->
<div class="container-fluid pt-5">
    <div class="text-center mb-4">
        <h2 class="section-title px-5"><span class="px-2">ĐÁNH GIÁ TỐT NHẤT</span></h2>
    </div>
    <div class="row px-xl-5 pb-3">
        @foreach (var p in product)
        {
            <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
                <div class="card product-item border-0 mb-4">
                    <div class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
                        <img class="img-fluid w-100" src="~/img/@p.Image" alt="">
                    </div>
                    <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
                        <h6 class="text-truncate mb-3">@p.Name</h6>
                        <div class="d-flex justify-content-center">
                            <h6>@(String.Format("{0:###,000}", (p.Price - (p.Price * p.Discount)))) VNĐ</h6><h6 class="text-muted ml-2"><del>@(String.Format("{0:###,000}",p.Price))</del></h6>
                        </div>
                    </div>
                    <div class="card-footer d-flex justify-content-between bg-light border">
                        <a asp-controller="ClothesDetails" asp-action="Index" asp-route-id="@p.Id" class="btn btn-sm text-dark p-0"><i class="fas fa-eye text-primary mr-1"></i>Chi Tiết</a>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <a asp-controller="CartItem" asp-action="AddToCart" asp-route-id="@p.Id" class="btn btn-sm text-dark p-0"><i class="fas fa-shopping-cart text-primary mr-1"></i>Thêm Giỏ Hàng</a>
                        }else{
                            <a asp-area="Identity" asp-page="/Account/Login" class="btn btn-sm text-dark p-0"><i class="fas fa-shopping-cart text-primary mr-1"></i>Thêm Giỏ Hàng</a>
                        }
                        
                    </div>
                </div>
            </div>
        }
    </div>
</div>