ClothesShop/Controllers/CartItemController.cs
using ClothesShop.Migrations;
using ClothesShop.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Internal;
using System.Collections.Generic;
using System.Linq;

namespace ClothesShop.Controllers
{
    public class CartItemController : Controller
    {
        public readonly ShopContext _shopContext;
        public readonly UserManager<AppUser> _userManager;
        public readonly SignInManager<AppUser> _signInManager;
        public List<Category> Category { get; set; }
        public List<CartModel> cartModels { set; get; }
        public CartItemController(ShopContext shopContext, UserManager<AppUser> userManager, SignInManager<AppUser> signInManager)
        {
            _shopContext = shopContext;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public IActionResult Index()
        {
            //lấy loại sản phẩm
            Category = (from a in _shopContext.Categories
                        where a.CateId < 3
                        select a).ToList();
            ViewData["category"] = Category;
            //lấy người dùng hiện tại đang hoạt động
            var userid = _userManager.GetUserId(User);

            //lấy danh sách sản phẩm 
            var z = _shopContext.Products.Select(p => p).ToList();
            ViewData["product"] = z;

            //lấy giỏ hảng theo người dùng đăng nhập
            cartModels = _shopContext.Carts.Where(p => p.UserId == userid).ToList();

            //tính tổng tiền trong giỏ hàng 
            var sum = _shopContext.Carts.Where(s => s.UserId == userid).Sum(x => x.ThanhTien);
            ViewBag.Sum = sum;
            return View(cartModels);
        }

        public IActionResult AddToCart(int id , int SoLuong)
        {
            
            var item = _shopContext.Carts.SingleOrDefault(p => p.Id == id);
            if(item == null)
            {
                if(SoLuong < 1)
                {
                    SoLuong = 1;
                    var product = _shopContext.Products.SingleOrDefault(p => p.Id == id);
                    var total = product.Price.Value - (product.Price.Value * product.Discount.Value);
                    item = new CartModel()
                    {
                        Price = total,
                        Quanlity = SoLuong,
                        ThanhTien = SoLuong * total,
                        Id = id,
                        UserId = _userManager.GetUserId(User),
                    };
                    _shopContext.Carts.Add(item);
                    _shopContext.SaveChanges();
                }
            }
            else
            {
                item.Quanlity++;
                _shopContext.SaveChanges();

            }
            
            return RedirectToAction("Index");
        }
        public IActionResult RemoveItem(int id) 
        {
            var item = _shopContext.Carts.SingleOrDefault(x => x.Id == id);
            if (item != null)
            {
                _shopContext.Carts.Remove(item);
            }
            _shopContext.SaveChanges();
            return RedirectToAction("Index");

        }
        public ActionResult UpdateItem(int id, int SoLuong)
        {
            var item = _shopContext.Carts.SingleOrDefault(x => x.Id == id);
            var product = _shopContext.Products.SingleOrDefault(p => p.Id == id);
            var total = product.Price.Value - (product.Price.Value * product.Discount.Value);
            if (item != null)
            {
                item.Quanlity = SoLuong;
                item.ThanhTien = SoLuong * total;
                _shopContext.SaveChanges();
            }
            
            return RedirectToAction("Index");
        }
    }
}

ClothesShop/Controllers/ShopController.cs
using ClothesShop.Helpers;
using ClothesShop.Migrations;
using ClothesShop.Models;
using Microsoft.AspNetCore.Authentication.OAuth.Claims;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Policy;
using System.Threading.Tasks;
using static System.Reflection.Metadata.BlobBuilder;

namespace ClothesShop.Controllers
{
    public class ShopController : Controller
    {
        private readonly ILogger<ShopController> _logger;
        public readonly ShopContext _shopcontext;

        public const int ITEMS_PER_PAGE = 9;
        [BindProperty(SupportsGet=true ,Name = "p")]
        public int currentPage { get; set; }
        public int countPage { get; set; }

        public ShopController(ILogger<ShopController> logger, ShopContext shopContext)
        {
            _logger = logger;
            _shopcontext = shopContext;
        }
        public List<Product> Products { get; set; }
        public List<Category> Category { get; set; } 

        public async Task<IActionResult> Man(int id,string sortOrder , string? searchString)
        {
            Category = (from a in _shopcontext.Categories
                        where a.CateId < 3
                        select a).ToList();
            ViewData["category"] = Category;
            if (id == 3)
            {
                Products = await (from c in _shopcontext.Products
                            where c.CateId == id
                            select c).ToListAsync();
            }
            else if (id == 2 || id == 1)
            {
                Products = await (from c in _shopcontext.Products
                            where c.CateId == id
                            where c.Gender == null || c.Gender == true
                            select c).ToListAsync();
            }

                        //==================SearchString======================
            ViewBag.url = "Man";
            if (!string.IsNullOrEmpty(searchString))
            {
                Products = Products.Where(a => a.Name.ToLower().Contains(searchString.ToLower())).ToList();
            }
            else
            {
                Products = Products.ToList();
            }

                        //==================SortOrder======================

            ViewBag.Price = sortOrder == "price" ? "price" : "price";
            ViewBag.Price_desc = sortOrder == "price_desc" ? "price_desc" : "price_desc";

            switch (sortOrder)
            {
                // 3.1 Nếu biến sortOrder sắp giảm thì sắp giảm theo Title
                case "price_desc":
                    Products = Products.OrderByDescending(p => p.Price - (p.Price * p.Discount)).ToList();
                    break;
                // 3.2 Sắp tăng dần theo price
                case "price":
                    Products = Products.OrderBy(p => p.Price - (p.Price * p.Discount)).ToList();
                    break;
            }


                         //===================== Paging ========================

            ViewBag.CurrentSort = sortOrder;
            ViewBag.SearchString = searchString;
            int totalProduct = Products.Count;
            countPage = (int)Math.Ceiling((double)totalProduct / ITEMS_PER_PAGE);
            if (currentPage < 1)
            {
                currentPage = 1;
            }
            if (currentPage > countPage)
            {
                currentPage = countPage;
            }
            var pagingmodel = new PagingModel()
            {
                currentpage = currentPage,
                countpage = countPage,
                generetUrl = (pag , sortOrder , searchString) => Url.Action("Man", new { p = pag , sortOrder = sortOrder , searchString  = searchString })
            };
            Products = Products.Skip((currentPage - 1) * 9).Take(ITEMS_PER_PAGE).ToList();
            ViewBag.pagingmodel = pagingmodel;
            return View("Index",Products);
        }


        public async Task<IActionResult> Women(int id , string sortOrder, string? searchString)
        {

            Category = (from a in _shopcontext.Categories
                        where a.CateId < 3
                        select a).ToList();
            ViewData["category"] = Category;
            ViewBag.url = "Women";
            if (id == 3)
            {
                Products = await (from c in _shopcontext.Products
                                  where c.CateId == id
                                  select c).ToListAsync();
            }
            else if (id == 2 || id == 1)
            {
                Products = await (from c in _shopcontext.Products
                                  where c.CateId == id
                                  where c.Gender == null || c.Gender == false
                                  select c).ToListAsync();
            }

                                //==================SearchString======================
            if (!string.IsNullOrEmpty(searchString))
            {
                Products = Products.Where(a => a.Name.ToLower().Contains(searchString.ToLower())).ToList();
            }
            else
            {
                Products = Products.ToList();
            }


                                //==================SortOrder======================

            ViewBag.Price = sortOrder == "price" ? "price" : "price";
            ViewBag.Price_desc = sortOrder == "price_desc" ? "price_desc" : "price_desc";
            switch (sortOrder)
            {
                // 3.1 Nếu biến sortOrder sắp giảm thì sắp giảm theo Title
                case "price_desc":
                    Products = Products.OrderByDescending(p => p.Price - (p.Price * p.Discount)).ToList();
                    break;
                // 3.2 Sắp tăng dần theo price
                case "price":
                    Products = Products.OrderBy(p => p.Price - (p.Price * p.Discount)).ToList();
                    break;
            }


                                //===================== Paging ========================

            ViewBag.CurrentSort = sortOrder;
            ViewBag.SearchString = searchString;
            int totalProduct = Products.Count;
            countPage = (int)Math.Ceiling((double)totalProduct / ITEMS_PER_PAGE);
            if (currentPage < 1)
            {
                currentPage = 1;
            }
            if (currentPage > countPage)
            {
                currentPage = countPage;
            }
            var pagingmodel = new PagingModel()
            {
                currentpage = currentPage,
                countpage = countPage,
                generetUrl = (pag, sortOrder , searchString) => Url.Action("Women", new { p = pag, sortOrder = sortOrder , searchString = searchString })
            };
            Products = Products.Skip((currentPage - 1) * 9).Take(ITEMS_PER_PAGE).ToList();
            ViewBag.pagingmodel = pagingmodel;

            return View("Index",Products);
        }


        public async Task<IActionResult> Index(string? searchString ,string sortOrder)
        {
            Category = await (from a in _shopcontext.Categories
                        where a.CateId < 3
                        select a).ToListAsync();
            ViewData["category"] = Category;
            ViewBag.url = "Index";

            //==================SearchString======================
            
            if (!string.IsNullOrEmpty(searchString))
            {
                Products = await _shopcontext.Products.Where(a => a.Name.ToLower().Contains(searchString.ToLower())).ToListAsync();
            }
            else
            {
                Products = await _shopcontext.Products.ToListAsync();
            }


                                //==================SortOrder======================

            ViewBag.Price = sortOrder == "price" ? "price" : "price";
            ViewBag.Price_desc = sortOrder == "price_desc" ? "price_desc" : "price_desc";

            switch (sortOrder)
            {
                // 3.1 Nếu biến sortOrder sắp giảm thì sắp giảm theo Title
                case "price_desc":
                    Products = Products.OrderByDescending(p => p.Price - (p.Price * p.Discount)).ToList();
                    break;
                // 3.2 Sắp tăng dần theo price
                case "price":
                    Products = Products.OrderBy(p => p.Price - (p.Price * p.Discount)).ToList();
                    break;
            }

                                //===================== Paging ========================


            ViewBag.CurrentSort = sortOrder;
            ViewBag.SearchString = searchString;
            int totalProduct = Products.Count;
            countPage = (int)Math.Ceiling((double)totalProduct / ITEMS_PER_PAGE);
            if (currentPage < 1)
            {
                currentPage = 1;
            }
            if (currentPage > countPage)
            {
                currentPage = countPage;
            }
            var pagingmodel = new PagingModel()
            {
                currentpage = currentPage,
                countpage = countPage,
                generetUrl = (pag, sortOrder,searchString) => Url.Action("Index", new { p = pag,sortOrder = sortOrder, searchString = searchString })
            };
            Products = Products.Skip((currentPage - 1) * 9).Take(ITEMS_PER_PAGE).ToList();
            ViewBag.pagingmodel = pagingmodel;

            return View(Products);

        }
    }
}

ClothesShop/Views/Shared/_AdminLayout.cshtml
@using Microsoft.AspNetCore.Authorization;
@inject IAuthorizationService authorizationService

@{
    var resultAuthorize =  await authorizationService.AuthorizeAsync(this.User, "ShowAdminMenu");
}

@if(resultAuthorize.Succeeded)
{
    <a asp-controller="Products" asp-action="Index" class="nav-item nav-link">Quản lý sản phẩm</a>
    <a asp-area="Admin" asp-page="/Role/Index" class="nav-item nav-link">Quản lý tài khoản</a>
}

ClothesShop/Views/Shared/_FooterPartial.cshtml
    <!-- Footer Start -->
<div class="container-fluid bg-secondary text-dark mt-5 pt-5">
    <div class="row px-xl-5 pt-5">
        <div class="col-lg-5 col-md-12 mb-5 pr-3 pr-xl-5">
            <a href="" class="text-decoration-none">
                <h1 class="mb-4 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border-white px-3 mr-1"><img style="height:50px" src="~/img/LOGO.png" /></span>Truly Vibes</h1>
            </a>
            <p>Truly Vibes sản phẩm thời trang chất lượng , uy tín .Luôn phục vụ khách hàng 1 cách tốt nhất ,đem lại cho khách hàng sự hài lòng và sự tin tưởng tốt nhất</p>
            <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>Đường Số 123,Nguyễn Văn Cừ ,Cần Thơ ,Việt Nam</p>
            <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>trulyvibesstudio@gmail.com</p>
            <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
        </div>
        <div class="col-lg-5 col-md-12" >
            <div class="row">
                <div class="col-md-4  mb-5">
                    <h5 class="font-weight-bold text-dark mb-4">Danh Mục</h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-dark mb-2" asp-action="Index" asp-controller="Home"><i class="fa fa-angle-right mr-2"></i>Trang Chủ</a>
                        <a class="text-dark mb-2" asp-action="Index" asp-controller="Shop"><i class="fa fa-angle-right mr-2"></i>Sản Phẩm</a>
                        <a class="text-dark mb-2" asp-action="Index" asp-controller="Cart"><i class="fa fa-angle-right mr-2"></i>Giỏ Hàng</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row border-top border-light mx-xl-5 py-4">
        <div class="col-md-6 px-xl-0">
            <p class="mb-md-0 text-center text-md-left text-dark">
                &copy; <a class="text-dark font-weight-semi-bold" href="#">Truly Vibes</a>. Luôn đặt uy tín và chất lượng lên hàng đầu.
            </p>
        </div>
        
    </div>
</div>
<a href="#" class="btn btn-primary back-to-top"><i class="fa fa-angle-double-up"></i></a>
<!-- Footer End -->

ClothesShop/Views/Shared/_Layout.cshtml
@{
    var category = ViewData["category"] as List<Category>;

}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link href="~/img/LOGO.png" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    
    <!-- Customized Bootstrap Stylesheet 600  -->
    <link href="~/css/style.css" rel="stylesheet">
    <link href="~/css/Star.css" rel="stylesheet">
   
</head>
<body>
    <div class="container-fluid">
        <div class="row align-items-center py-3 px-xl-5">
            <div class="col-lg-3 d-none d-lg-block">
                <a asp-controller="Home" asp-action="Index" class="text-decoration-none">
                    
                    <h1 class="m-0 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold px-3 mr-1"><img style="height:45px"src="~/img/LOGO.png" /></span>Truly Vibes</h1>
                </a>
            </div>

            <div class="col-lg-6 col-6 text-left">
                <form method="get" asp-controller="Shop" asp-action="@ViewBag.url">
                    <div class="input-group">
                        <input type="text" name="searchString" class="form-control" placeholder="Tìm Kiếm Sản Phẩm">
                        <div class="input-group-append">
                            <button type="submit" class="input-group-text bg-transparent text-primary">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-3 col-6 text-right">
                <a asp-controller="CartItem" asp-action="Index" class="btn border">
                    <i class="fas fa-shopping-cart text-primary"></i>
                    <span class="badge"></span>
                </a>
            </div>
        </div>
    </div>
    <!-- Navbar Start -->
    <div class="container-fluid">
        <div class="row border-top px-xl-5">
            <div class="col-lg-3 d-none d-lg-block">
                <a class="btn shadow-none d-flex align-items-center justify-content-between bg-primary text-white w-100" data-toggle="collapse" href="#navbar-vertical" style="height: 65px; margin-top: -1px; padding: 0 30px;">
                    <h6 class="m-0">Thể Loại</h6>
                    <i class="fa fa-angle-down text-dark"></i>
                </a>
                <nav class="collapse position-absolute navbar navbar-vertical navbar-light align-items-start p-0 border border-top-0 border-bottom-0 bg-light" id="navbar-vertical" style="width: calc(100% - 30px); z-index: 1;">
                    <div class="navbar-nav w-100 overflow-hidden" style="height: 162px">
                        @foreach(var  p in category)
                        {
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link" data-toggle="dropdown">@p.CateName <i class="fa fa-angle-down float-right mt-1"></i></a>
                               
                                <div class="dropdown-menu position-absolute bg-secondary border-0 rounded-0 w-100 m-0">
                                    <a asp-controller="Shop" asp-action="Man" asp-route-id="@p.CateId"  class="dropdown-item">Nam</a>
                                    <a asp-controller="Shop" asp-action="Women" asp-route-id="@p.CateId" class="dropdown-item">Nữ</a>
                                </div>
                            </div>
                        }
                        <a asp-controller="Shop" asp-action="Man" asp-route-id="3" class="nav-item nav-link">Phụ Kiện</a>
                    </div>
                </nav>
            </div>
            <div class="col-lg-9">
                <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0">
                    <a asp-controller="Home" asp-action="Index" class="text-decoration-none d-block d-lg-none">
                        <h1 class="m-0 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold  px-3 mr-1"><img style="height:50px" src="~/img/LOGO.png" /></span>Truly Vibes</h1>
                    </a>
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                        <div class="navbar-nav mr-auto py-0">
                            <a asp-controller="Home" asp-action="Index" class="nav-item nav-link">Trang Chủ</a>
                            <a asp-controller="Shop" asp-action="Index" class="nav-item nav-link">Sản Phẩm</a>
                            <partial name="_AdminLayout"/>
                        </div>
                        <partial name="_LoginPartial"/>
                    </div>
                </nav>
            </div>
        </div>
    </div>
    <!-- Navbar End -->
    <div class="container-fluid p-0">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
   
    <partial name="_FooterPartial.cshtml" />
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="~/lib/easing/easing.min.js"></script>

    <!-- Contact Javascript File -->
    <script src="~/mail/jqBootstrapValidation.min.js"></script>
    <script src="~/mail/contact.js"></script>

    <!-- Template Javascript -->
    <script src="~/js/main.js"></script>
    <script src="~/js/Starjs.js"></script>
    @RenderSection("Scripts", required: false)
    
</body>
</html>

ClothesShop/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/img/LOGO.png" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet 600  -->
    <link href="~/css/style.css" rel="stylesheet">
    <link href="~/css/Login.css" rel="stylesheet">
</head>
<body>
    <div class="container-fluid">
        <div class="row align-items-center py-3 px-xl-5">
            <div class="col-lg-3 d-none d-lg-block">
                <a asp-controller="Home" asp-action="Index" class="text-decoration-none">
                    <h1 class="m-0 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold px-3 mr-1"><img style="height:50px" src="~/img/LOGO.png" /></span>Truly Vibes</h1>
                </a>
            </div>
         </div>
    </div>
    <div class="container-fluid">
        <div class="row border-top px-xl-5">
            <div class="col-lg-9">
                <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0">
                    <a asp-controller="Home" asp-action="Index" class="text-decoration-none d-block d-lg-none">
                        <h1 class="m-0 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold  px-3 mr-1"><img style="height:50px" src="~/img/LOGO.png" /></span>Truly Vibes</h1>
                    </a>
                </nav>
            </div>
        </div>
    </div>
    @RenderSection("breadcrum", required: false)
    <div class="container-fluid p-0">
            @RenderBody()
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/easing/easing.min.js"></script>
    <script src="~/lib/owlcarousel/owl.carousel.min.js"></script>

    <!-- Contact Javascript File -->
    <script src="~/mail/jqBootstrapValidation.min.js"></script>
    <script src="~/mail/contact.js"></script>

    <!-- Template Javascript -->
    <script src="~/js/main.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ClothesShop/Views/Shared/_Paging.cshtml
@*
    Model:
      - currentPage:int - Trang hiện tại
      - countPages:int - tổng số trang
      - generateUrl:delegate Func<int?, string> trả về URL tương ứng với trang p (1,2,3 ...)
*@

@model ClothesShop.Helpers.PagingModel
@{
    int currentPage = Model.currentpage;
    int countPages = Model.countpage;
    var generateUrl = Model.generetUrl;

    if (currentPage > countPages)
        currentPage = countPages;

    if (countPages <= 1) return;


    int? preview = null;
    int? next = null;

    if (currentPage > 1)
        preview = currentPage - 1;

    if (currentPage < countPages)
        next = currentPage + 1;

    // Các trang hiện thị trong điều hướng
    List<int> pagesRanges = new List<int>();


    int delta = 5;             // Số trang mở rộng về mỗi bên trang hiện tại
    int remain = delta * 2;     // Số trang hai bên trang hiện tại

    pagesRanges.Add(currentPage);
    // Các trang phát triển về hai bên trang hiện tại
    for (int i = 1; i <= delta; i++)
    {
        if (currentPage + i <= countPages)
        {
            pagesRanges.Add(currentPage + i);
            remain--;
        }

        if (currentPage - i >= 1)
        {
            pagesRanges.Insert(0, currentPage - i);
            remain--;
        }

    }
    // Xử lý thêm vào các trang cho đủ remain
    //(xảy ra ở đầu mút của khoảng trang không đủ trang chèn  vào)
    if (remain > 0)
    {
        if (pagesRanges[0] == 1)
        {
            for (int i = 1; i <= remain; i++)
            {
                if (pagesRanges.Last() + 1 <= countPages)
                {
                    pagesRanges.Add(pagesRanges.Last() + 1);
                }
            }
        }
        else
        {
            for (int i = 1; i <= remain; i++)
            {
                if (pagesRanges.First() - 1 > 1)
                {
                    pagesRanges.Insert(0, pagesRanges.First() - 1);
                }
            }
        }
    }

}

@* PHÁT SINH HTML*@

<ul class="pagination">
    <!-- Previous page link -->
    @if (preview != null)
    {
        <li class="page-item">
            <a class="page-link" href="@generateUrl(preview,@ViewBag.CurrentSort,@ViewBag.SearchString)">Trang trước</a>
        </li>
    }
    else
    {
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Trang trước</a>
        </li>
    }

    <!-- Numbered page links -->
    @foreach (var pageitem in pagesRanges)
    {
        if (pageitem != currentPage)
        {
            <li class="page-item">
                <a class="page-link" href="@generateUrl(pageitem,@ViewBag.CurrentSort,@ViewBag.SearchString)">
                    @pageitem
                </a>
            </li>
        }
        else
        {
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="#">@pageitem <span class="sr-only">(current)</span></a>
            </li>
        }
    }


    <!-- Next page link -->
    @if (next != null)
    {
        <li class="page-item">
            <a class="page-link" href="@generateUrl(next,@ViewBag.CurrentSort,@ViewBag.SearchString)">Trang sau</a>
        </li>
    }
    else
    {
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Trang sau</a>
        </li>
    }
</ul>